### PR TITLE
Odroidxu4 v4.6.3 add HDMI output to kernel

### PR DESCRIPTION
**Pull request by rhkean**
a few more additions are required to enable the HDMI output

### CODE REVIEW

**Comment by tobetter** [comment]
@rhkean Thank you for the patches, I only found **odroidxu4_defconfig** is different against to my branch. Before I merge the commit https://github.com/tobetter/linux/pull/7/commits/1e9f7e9f7c595787963d280a05ce7495b2776f4a, I am curious **CONFIG_DRM_EXYNOS_DSI**, **CONFIG_DRM_EXYNOS_DP** and **CONFIG_DRM_PANEL** are necessary to be enabled, since XU4 does not have such interface.

**Comment by rhkean** [comment]
I think _CONFIG_DRM_EXYNOS_DP_ is required.  I'm running a build now to test.  If so, I'll correct the pull and let you know.

**Comment by rhkean** [comment]
ok....   **CONFIG_DRM_PANEL** get enabled automatically when you enable **CONFIG_DRM_EXYNOS_DP** (display port)

Just enabling **CONFIG_DRM_EXYNOS_HDMI** + **CONFIG_DRM_EXYNOS_DP**  does not work.

I'm testing  **CONFIG_DRM_EXYNOS_HDMI** + **CONFIG_DRM_EXYNOS_DSI** now.

**Comment by rhkean** [comment]
OK... I'm going to have to pick this up again tomorrow.  I just re-enabled everything and it's not working.... I think I have a typo in my script or something and it's late.

**Comment by tobetter** [comment]
@rhkean Thank you for the patch, instead of pulling your patch to my branch I've done cherry-pick since my branch is updated with 4.6.3 after you fork my branch. :) If you want to have same branch on yours, please push mine to yours with 'git push -f ...'.
https://github.com/tobetter/linux/commits/odroidxu4-v4.6

New kernel package is going to be built and uploaded.
https://code.launchpad.net/~tobetter/odroid-image/odroidxu4-v4.6

**Comment by rhkean** [comment]
I already sync'd my fork to your branch.  the only change in this pull is the odroidxu4_defconfig file.

But, if you're done with this pull, it can be closed.  I'm glad I was able to contribute.

**Comment by rhkean** [comment]
@tobetter 
I just looked at your changes to the odroid_xu4_defconfig file.

you also need these from my latest pull (about 6 hours ago... looks like we were both working on it at the same time): 

#changed automatically when changing the CONFIG_DRM setting to "y"
- CONFIG_I2C_ALGOBIT=y  

#needs to be built-in to function with minimal uInitrd files that don't contain modules
- CONFIG_DRM=y  
- CONFIG_DRM_EXYNOS=y

#these are needed by the built-in framebuffer driver
- CONFIG_FB_SYS_FILLRECT=y
- CONFIG_FB_SYS_COPYAREA=y
- CONFIG_FB_SYS_IMAGEBLIT=y
- CONFIG_FB_SYS_FOPS=y

**Comment by tobetter** [comment]
@rhkean I just took the two commits for HDMI from you branch and merged into mine. I didn't do the same work with you, just verified your patch. :) Please check commit history on my branch.
https://github.com/tobetter/linux/commits/odroidxu4-v4.6

**Comment by rhkean** [comment]
@tobetter 
sorry, I just looked at the diffs.... my apologies.

I'm running a build off of your current tree now to confirm.  It should be done in about 30 minutes.

If it builds and initializes the HDMI display, I'll close this pull.  If not, I'll let you know.

**Comment by rhkean** [comment]
@tobetter 
All looks good.  Sorry for the confusion.

**Comment by tobetter** [comment]
@rhkean No worries, nothing wrong. Good to hear your build works for you. Hope to get another patches from you. :)

**Pull request closed without merging**
